name: 'Package Version Checker'
description: 'Checks for valid Package Version'
author: 'Author Name'

inputs:
  token:
    description: 'GitHub token'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'dist/package-version-checker/index.js'
