name: 'Package Version Checker'
description: 'Checks for valid Package Version'
author: 'Author Name'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'node12'
  main: 'dist/package-version-checker'
