name: Version Checker

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: [main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
