name: Github Action

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: goverdhan6174/first-github-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
